version: "3.1"

services:
  db:
    build:
      context: .
      dockerfile: ./db.dockerfile
    ports:
      - 5434:5432

  # Make a test service b/c accessing the docker-hosted db on CircleCI is easiest from another service.
  tests:
    build:
      context: .
      dockerfile: ./tests.dockerfile
    depends_on:
      - db
    env_file: ./env.docker
