version: "3.1"

services:
  db:
    build:
      context: ./
      dockerfile: db.dockerfile
    ports:
      - 5435:5432
    command:
      - "postgres"
      - "-c"
      - "fsync=off"

  # Make a test service b/c accessing the docker-hosted db on CircleCI is easiest from another service.
  tests:
    build:
      context: .
      dockerfile: ./tests.dockerfile
    depends_on:
      - db
    env_file:
      - local.env
      - local.docker.env
